stripe:
    binarizer:
        h_min: 0
        h_max: 30

    median_blur:
        ksize: 5

    equalizer:
        unused: 0.01

    stripes:
        min_sides_ratio: 1.5
        min_length: 10
        min_width: 10

    approx_dist: 3.0

gate:
    red_stripe:
        binarizer:
            h_min: -20
            h_max: 50

        median_blur:
            ksize: 5

        equalizer:
            unused: 0.01

        enable_col_cor: 1
        stripes:
            sides_ratio: 1.5
            approx_diff: 3.0
            # min_length: 5
            max_width: 10

    green_stripe:
        binarizer:
            h_min: 60
            h_max: 85
            s_min: 125
            s_max: 160
            v_min: 100
            v_max: 150

        median_blur:
            ksize: 7

        equalizer:
            unused: 0.01
        stripes:
            sides_ratio: 1.5
            approx_diff: 3.0
            # min_length: 5
            max_width: 20

fargate:
    median_big:
        ksize: 17
    median:
        ksize: 5

    dilate:
        side_: 7

    hsv:
        # h_max: 5
        s_max: 70
        v_min: 240

    approx_dist: 1

    unused: 0.01
    channels_count: 0

    dx: 1
    most_common_part: 0.05
    min_gate_width: 150
    cell_pixels: 2
    hough_thresh: 0.13

