float64 real_period

navig/MsgAgeInfo dvl_down
navig/MsgAgeInfo supervisor_depth
navig/MsgAgeInfo dvl_plane_velocity
navig/MsgAgeInfo compass_angle
navig/MsgAgeInfo compass_angle_rate
navig/MsgAgeInfo compass_acceleration


bool velocity_flag
bool position_flag


navig/MsgPlaneVelocity velocity_acc
navig/MsgPlaneVelocity velocity


navig/MsgLocalPosition position_acc
navig/MsgLocalPosition position_dvl
navig/MsgLocalPosition position