initial_depth: 0.3
initial_thrust: 0.07

timeout_init: 30
timeout_lane_search: 10
timeout_fix_lane: 60
timeout_open_bin: 100

timeout_position: 20
fix_by_position: true
real_lane_width: 0.30
fix_p: 0.2
fix_d: 0.6

eps_distance: 0.04
eps_angle: 5
success_time: 5
lanes_needed: 3

bin_height: 1.10
move_down_timeout: 15
bin_frame_offset: 0.2
timeout_backward: 7
thrust_backward: 0.02

distance_uncover: 0.5
thrust_uncover: 0.05
timeout_uncover: 5

