timeout_initialization: 10
timeout_listen_first_ping: 25
timeout_go_flare: 60
timeout_bump_flare: 10
timeout_finalize: 5
timeout_regul: 3
timeout_lose_pinger: 5
start_depth: 1.0
heading_delta: 30
thrust_close_in: 0.2
thrust_finalize: 0.1
close_in_border: 0.2
infinity: 1.0e5
pings_needed: 3
filter_size: 3
use_median: false
