timeout_initialization: 10
timeout_looking_for_gate: 0
# timeout_looking_for_gate: 20
timeout_stabilize_gate: 0
# timeout_stabilize_gate: 10
timeout_proceed_gate: 40
start_depth: 1.0
heading_delta: 20
thrust_initial_search: 0.1
thrust_stabilize: 0.1
proceed_thrust: 0.2
proceed_distance: 5.0
gate_ratio: 0.7
gate_real_size: 3.05
large_count_needed: 3
distance_after_gate: 2.0
