timeout_initialization: 10
timeout_looking_for_gate: 20
timeout_stabilize_gate: 20
timeout_proceed_gate: 40
start_depth: 1.0
heading_delta: 20
thrust_initial_search: 0.15
thrust_stabilize: 0.15
proceed_thrust: 0.2
proceed_distance: 8.5
# proceed_distance: 9.5
gate_ratio: 0.7
gate_real_size: 3.05
large_count_needed: 3
distance_after_gate: 2.0
