stop_after_fail: false
tasks:
    -
        name: gate_task
        params:
            timeout_total: 100
    -
        name: orange_lane_task
        params:
            timeout_total: 20
            relative_heading: -7
    -
        name: buoy_task
        params:
            timeout_total: 150
            # relative_heading: 10
    -
        name: orange_lane_task
        params:
            timeout_total: 20
    -
        name: navigate_channel_task
        params:
            timeout_total: 100
            # relative_heading: 5
    -
        name: pinger_task
        params:
            timeout_total: 200
            # zone_name: octagon
            # zone_name: bins

bins:
    -
        name: bins_task
        params:
            timeout_total: 200
    -
        name: pinger_task
        params:
            timeout_total: 200
            zone_name: octagon

octagon:
    -
        name: pinger_task
        params:
            zone_name: bins
            timeout_total: 200
