initial_thrust: 0.2
timeout_init: 1
timeout_lane_search: 10
timeout_fix_lane: 30

timeout_position: 20
fix_by_position: false
real_lane_width: 20
fix_p: 0.75
fix_d: 1.5

eps_distance: 0.04
eps_angle: 5
success_time: 5
lanes_needed: 3