timeout_initialization: 10
timeout_bearing_targeting: 120
timeout_coordinates_targeting: 20
timeout_finalize: 10

period_pinger_emit: 1

targeting_type: "bearing"

pinger_depth: 1.73
dive_depth: 0.5

bearing_thrust: 0.4

data_weight: 0.2

finalize_distance: 0.5