start_depth: 1.5
timeout_initialization: 10
timeout_listen_pings: 50
timeout_pinger_listening: 30
timeout_pinger_selection: 5
timeout_bearing_targeting: 150
timeout_coordinates_targeting: 15
timeout_finalize: 10

timeout_lift_up: 20

period_pinger_emit: 2.0
period_vehicle_rotating: 2.0

delta_rotating: 15.0

lift_up_distance: 2.0
zone_threshold_distance: 4.0
bearing_thrust: 0.2

far_thrust: 0.20
near_thrust: 0.10
far_thrust_period: 3.0
near_thrust_period: 1.5

lift_up_count: 5

selection_window_size: 5

heading_threshold: 45

timeout_coordinate: 20

data_weight: 0.4

pinger_distance_threshold: 30