frequency: 20
timeout_silence: 3
timeout_not_respond: 2
regulators: ["thrust", "depth", "heading", "pitch", "position", "height", "target", "target_distance"]
params:
    depth:
        kp: 0.35
        ki: 0.0
        kd: 0.9
        accuracy: 0.15
        # buoyancy_thrust: 0.10
        # buoyancy_thrust: 0.05
        buoyancy_thrust: 0.08



    target_distance:
        dependencies: ["target"]

        kp: 0.5
        ki: 0.0
        kd: 1.0

        accuracy: 0.10

    target:
        dependencies: ["heading"]

    heading:
        kp: 0.02
        ki: 0.0
        kd: 0.01
        accuracy: 2.865

    pitch:
        kp: 0.01
        ki: 0.0
        kd: 0.01
        accuracy: 2.865

    position:
        dependencies: ["heading"]
        cruiser_dist: 5.0

        fwd_kp: 0.5
        fwd_ki: 0.0
        fwd_kd: 1.0

        side_kp: 0.5
        side_ki: 0.0
        side_kd: 1.0

        accuracy: 0.10


limits:
    forward: 0.5
    right: 0.3
    down: 0.7
    mforward: 0.3
    mright: 0.3
    mdown: 0.2
