settings:
    default_path: storage/
    default_block_size: 512

bags:
    -   name: vision
        params:
            node_base: false
            include_topics: ["/camera/(front|bottom)/image_raw",
                             "/vision/Image",
                             "/vision/(Msg(.*))|(Cmd(.*))",
                             "/navig/MsgOdometry",
                             "/mission(.*)",
                             "/navig(.*)",
                             "/motion(.*)",
                             "/supervisor/CmdDeviceKey",
                             "/tcu/CmdForce"]
            exclude_topics: []
    -   name: telemetry
        params:
            node_base: false
            include_topics: ["/dsp(.*)",
                             "/dvl(.*)",
                             "/navig(.*)",
                             "/motion(.*)",
                             "/supervisor(.*)",
                             "/tcu(.*)"]
            exclude_topics: []