#ifndef CAS_ALARMS
#define CAS_ALARMS

#include <string>
typedef enum
{
	MISSION_IDLE, MISSION_START, MISSION_END, 
	MISSION_TIMEOUT, TASK_START, TASK_FINISHED, TASK_TIMEOUT, 
	STATE_START, OBJECT_FOUND, STATE_SUCCESS, STATE_TIMEOUT, 
	ALARM_STOP, ALARMS_VALUE
} cas_alarm;

const std::string alarm_names[ALARMS_VALUE] = 
	{"MISSION_IDLE", "MISSION_START", "MISSION_END", 
	 "MISSION_TIMEOUT", "TASK_START", "TASK_FINISHED", "TASK_TIMEOUT", 
	 "STATE_START", "OBJECT_FOUND",	"STATE_SUCCESS", "STATE_TIMEOUT",
	 "ALARM_STOP"};

#endif