#ifndef HEADERS_H
#define HEADERS_H

enum TCP_HEADERS {
    CAN_HEADER,
    FIRMWARE_COMMAND_HEADER,
    FIRMWARE_PACKET_HEADER,
    MANIP_HEADER,
    LIGHT_HEADER,
    LIGHT_RGB_HEADER,
    SWITCH_DEVICES_HEADER,
    IMU_HEADER,
    ECHO_HEADER,
    GANS_HEADER,
    CAMERA_HEADER,
    UART_HEADER,
    PWM_HEADER,
    UDP_CONF_HEADER,
    SYSTEM_FLAGS_HEADER,
    CAS_CONFIG,
    CAS_COMMAND
};

enum UDP_HEADERS {
    GYRO_HEADER = 128,
    ACCELEROMETER_HEADER = 129,
    COMPASS_HEADER = 130,
    DEPTH_SENSOR_HEADER = 131,
    INNER_PRESURE_HEADER = 132,
    FACILITIES_HEADER = 133,
    LEAK_HEADER = 134,
    FIRMWARE_READY_HEADER = 135,
    SHORT_CIRCUIT_HEADER = 136,
    ADC_HEADER = 137, // АЦП
    ADC_EXTERNAL_HEADER = 138,
    COMPENSATOR_HEADER = 139
};

enum SUCAN_KEYS {
    SUCAN_GRABBER = 1,
    SUCAN_DSP = 4,
    SUCAN_CARGO_1 = 5,
    SUCAN_CARGO_2 = 6,
    SUCAN_TORPEDO_1 = 8,
    SUCAN_TORPEDO_2 = 2, 
    SUCAN_DVL = 7
};

#endif // HEADERS_H
