#include <compass/MsgAngle.h>
#include <compass/MsgAcceleration.h>
#include <compass/MsgAngleRate.h>
#include <navig/MsgEstimatedPosition.h>
#include <dvl/MsgDistance.h>
#include <dvl/MsgVelocity.h>
#include <dvl/MsgHeight.h>
#include <gps/MsgGpsCoordinate.h>
#include <gps/MsgGpsSatellites.h>
#include <gps/MsgGpsUtc.h>
#include <supervisor/MsgDepth.h>